export const ROLES = [
    'ROLE_UE21_ACADEMIA_VISUALIZACION_CARRERAS',
    'ROLE_UE21_ACADEMIA_GESTION_CARRERAS',
    'ROLE_UE21_ACADEMIA_VISUALIZACION_PLANES',
    'ROLE_UE21_ACADEMIA_GESTION_PLANES',
    'ROLE_UE21_ACADEMIA_VISUALIZACION_MATERIAS',
    'ROLE_UE21_ACADEMIA_GESTION_MATERIAS',
    'ROLE_UE21_ACADEMIA_APROBADOR_PLANES'
];

export const STATE_LOGIN = {
    user: {
        authorities: [
            'ROLE_UE21_ACADEMIA_VISUALIZACION_CARRERAS',
            'ROLE_UE21_ACADEMIA_GESTION_CARRERAS',
            'ROLE_UE21_ACADEMIA_VISUALIZACION_PLANES',
            'ROLE_UE21_ACADEMIA_GESTION_PLANES',
            'ROLE_UE21_ACADEMIA_VISUALIZACION_MATERIAS',
            'ROLE_UE21_ACADEMIA_GESTION_MATERIAS',
            'ROLE_UE21_ACADEMIA_APROBADOR_PLANES'
        ],
        id: 'MARTBRACAMONTE',
        name: 'MARTBRACAMONTE',
        email: null
    }
};
