server:
  port: ${PRICING_BFF_PORT:8081}
  servlet:
    context-path: /
    session:
      cookie:
        name: PRICINGAUTH2SESSION
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 32KB
  use-forward-headers: true
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    accesslog:
      enabled: false

logging:
  level:
    org.springframework.security: DEBUG
pricing-ues21-bff-dev:
  pricing-ues21-backend:
    base-url: ${PRICING_PRICING_BACKEND:http://localhost:8080/}

  oauth.server: ${PRICING_OAUTH_SERVER:http://ecampus2-trimix.uesiglo21.edu.ar:8080}
  oauth.clientId: ${PRICING_OAUTH_CLIENT_ID_BACKEND:desa}
  oauth.clientsecret: ${PRICING_OAUTH_CLIENT_SECRET_BACKEND:desa}

oauth:
  retrofit:
    oauthUrl: ${pricing-ues21-bff-dev.oauth.server}/menu/api/oauth2/
    clientid: ${pricing-ues21-bff-dev.oauth.clientId}
    clientsecret: ${pricing-ues21-bff-dev.oauth.clientsecret}
security:
  oauth2:
    client:
      client-id: ${pricing-ues21-bff-dev.oauth.clientId}
      client-secret: ${pricing-ues21-bff-dev.oauth.clientsecret}
      accessTokenUri: ${pricing-ues21-bff-dev.oauth.server}/menu/api/oauth2/token
      userAuthorizationUri: ${pricing-ues21-bff-dev.oauth.server}/menu/api/oauth2/authorize
      token-name: oauth_token
      authentication-scheme: query
      client-authentication-scheme: form
    resource:
      userInfoUri: ${pricing-ues21-bff-dev.oauth.server}/menu/api/oauth2/user
      filter-order: 3
spring:
  session:
    servlet:
      filterOrder: -2147483648

service:
  name: ${PRICING_SERVICE_NAME:pricing-bff-dev}
  instance: ${PRICING_HOSTNAME:http://localhost:8088}

management:
  endpoints:
    web:
      exposure:
        include: "*"